version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - java -version
      - mvn package
artifacts:
  files:
    - target/sample-app-1.0.jar
  discard-paths: yes
